targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          store_date_time_values_as_text: true
      json_serializable:
        enabled: true
        options:
          any_map: true
          checked: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
